# Generated by Django 3.2.9 on 2021-12-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='commnet',
            new_name='comment',
        ),
    ]
